Repository Agoric/documentation, pull requests merged in 2020-04, with the labels that each got.

#106 docs: update ERTP API doc to reflect the treatment of promises
  main/ertp/api/issuer.md
  main/ertp/api/purse.md
Labels: Contract Developer Experience, ERTP

#111 docs: explain how to import the zoeHelper functions.
  main/zoe/api/zoe-helpers.md
Labels: Contract Developer Experience, Zoe, hackathon-release

#118 feat: add generic guide to Agoric Dapps
  main/.vuepress/themeConfig/nav.js
  main/dapps/README.md
Labels: hackathon-release

#119 fix: remove old smart contract tutorials
  main/.vuepress/config.js
  main/smart-contracts-tutorials/guess37-multiple.md
  main/smart-contracts-tutorials/guess37-one.md
Labels: hackathon-release

#109 Glossary
  main/.vuepress/themeConfig/nav.js
  main/glossary/README.md
Labels: hackathon-release

#100 Creating-and-Starting-Demo-Projects.md added
  main/getting-started/start-a-project/README.md
Labels: hackathon-release

#98 Agoric CLI commands
  main/getting-started/agoric-cli-guide/README.md
Labels: hackathon-release

#97 [ERTP]: Created Intro to ERTP doc
  main/getting-started/ertp-introduction/README.md
Labels: hackathon-release

#93 Before using Agoric software
  main/getting-started/before-using-agoric/README.md
Labels: hackathon-release

#92 Documentation Guide and Structure
  main/getting-started/README.md
Labels: hackathon-release

#154 fix: update zoe version, roadmap
  main/.vuepress/config.js
  main/zoe/roadmap/README.md
Labels: hackathon-release

#155 First draft of contract requirements
  main/.vuepress/config.js
  main/zoe/guide/contract-requirements.md
Labels: hackathon-release

#156 feat: add links to definitions, including records
  main/zoe/api/records.md
  main/zoe/api/zoe-contract-facet.md
  main/zoe/api/zoe.md
Labels: hackathon-release

#166 Docs: Improved description of our programming environment
  main/distributed-programming.md
Labels: Contract Developer Experience, ERTP, hackathon-release
