Repository Agoric/documentation, pull requests merged in 2022-03, with the labels that each got.

#635 style: Italicize in-page links
  main/.vuepress/config.js
Labels: glossary

#639 ci(build-deploy-doc): ensure we don't modify yarn.lock
  .github/workflows/build-deploy-doc.yml
Labels: bug

#641 fix: forward to main site for errors
  _redirects
Labels: bug

#649 fix: Cleanup the Dapp Guide
  main/dapps/README.md
  main/getting-started/deploying.md
  main/getting-started/start-a-project.md
Labels: Contract Developer Experience

#638 fix: Clean up the glossary
  main/getting-started/before-using-agoric.md
  main/getting-started/intro-zoe.md
  main/glossary/README.md
  main/zoe/api/zoe.md
  main/zoe/guide/proposal.md
Labels: glossary
