Repository Agoric/documentation, pull requests merged in 2024-01, with the labels that each got.

#873 Adds SubQuery to Integration section
  main/.vuepress/config.js
  main/guides/subquery-indexing.md
Labels: automerge:squash

#908 docs(subquery): fix typo, missing space
  main/guides/subquery-indexing.md
Labels: automerge:merge

#904 docs(agoric-cli): add agoric run; deprecate beta features
  main/guides/agoric-cli/README.md
  main/guides/getting-started/README.md
Labels: automerge:merge

#910 getting-started: make all commands user runs use codeblock
  main/guides/getting-started/README.md
Labels: automerge:rebase

#911 unblurry version of `yarn start:ui` output
  main/guides/getting-started/assets/044.png
Labels: automerge:rebase
